### ISSUE TITLE
Failed to activate the terminal package

### ISSUE THREAD

**Issue by dwillitzer** [atom-archive/terminal#56] opened 2015-06-10 07:52 UTC
[Enter steps to reproduce below:]
1. Updated to version below, throws errors not a function.  
   **Atom Version**: 0.208.0
   **System**: Mac OS X 10.10.4
   **Thrown From**: [terminal](https://github.com/atom/terminal) package, v0.28.0
### Stack Trace

Failed to activate the terminal package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/DJ/.atom/packages/terminal/lib/terminal.coffee:13:18)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -1:41.7.0 emmet:remove-tag (atom-text-editor.editor.is-focused)
     -1:39.9.0 core:undo (atom-text-editor.editor.is-focused)
  8x -1:39.3.0 emmet:encode-decode-data-url (atom-text-editor.editor.is-focused)
     -1:17 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:54.8.0 command-palette:toggle (table.native-key-bindings.table.text)
     -0:52.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:49 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:47.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:47.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:44 project-manager:toggle (table.native-key-bindings.table.text)
     -0:42.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:42.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:39.4.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
     -0:34.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:34.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  3x -0:34.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "silent-sync",
      "remote-edit"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal, vundefined
atomatigit, v1.5.3
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.6
autocomplete-phpunit, v1.0.2
autocomplete-sass, v0.1.0
browser-refresh, v0.9.0
color-picker, v2.0.4
command-logger, v0.23.0
css-comb, v2.0.4
editor-stats, v0.17.0
emmet, v2.3.10
file-icons, v1.5.7
git-log, v0.4.1
git-tab-status, v1.9.2
language-htaccess, v0.1.1
linter-bootlint, v0.0.6
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-phpmd, v0.0.11
meteor-api, v2.19.0
minimap, v4.9.4
minimap-git-diff, v4.1.3
pretty-json, v0.3.3
project-colorize, v0.2.0
project-manager, v1.15.10
project-palette-finder, v2.4.17
react, v0.12.0
remote-atom, v1.2.6
remote-sync, v3.1.2
search, v0.5.0
seti-syntax, v0.4.0
seti-ui, v0.7.1
slack-chat, v3.0.1
ssh-config, v0.10.1
svg-preview, v0.6.0
terminal, v0.28.0
todo-show, v0.12.0
tree-view-git-status, v0.1.1
webbox-color, v0.5.7
wordpress, v0.2.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by bsr203** [comment] 2015-06-18 12:33
I too have same issue.

The dependencies in package.json has a version of `pty.js` point to a custom one

```
"dependencies": {
    "pty.js": "http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz",

```

when I build with it, I get error.

```
Installing modules ✗
> pty.js@0.2.4 install /Users/bsr/Work/Tools/repo/terminal/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

In file included from ../src/unix/pty.cc:16:
../node_modules/nan/nan.h:352:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:332:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:356:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:337:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:356:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

It builds fine with any of the official `pty.js` (tried with all the versions 2.4 till 2.7.1 from https://github.com/chjj/pty.js/releases). After apm link, when atom opens it gives the `undefined` error as reported by @djdesign

**Comment by pasi1** [comment] 2015-08-19 22:14
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [terminal](https://github.com/atom/terminal) package, v0.28.0

### Stack Trace

Failed to activate the terminal package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/home/piotr/.atom/packages/terminal-master/lib/terminal.coffee:13:18)
  at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:243:19)
  at /opt/atom/resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/atom/resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:486:21)
  at /opt/atom/resources/app.asar/src/package-manager.js:469:29
  at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/opt/atom/resources/app.asar/src/package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app.asar/src/package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (/opt/atom/resources/app.asar/src/atom.js:673:21)
  at Object.<anonymous> (/opt/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/opt/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///opt/atom/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///opt/atom/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2018-08-23 19:47
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed as completed by lee-dohm** 2018-08-23 19:47 UTC
