### ISSUE TITLE
terminal@0.28.0 failed to install

### ISSUE THREAD

**Issue by lovebug356** [atom-archive/terminal#33] opened 2014-04-07 15:25 UTC
Terminal failed to install with this output:

```
> pty.js@0.2.4 install /private/var/folders/jb/3wmdzhj53jb5l4tkwchty0w80000gn/T/apm-install-dir-11437-10619-1bk5huy/node_modules/terminal/node_modules/pty.js
> node-gyp rebuild


npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/guid/0.0.10
npm http GET http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/emissary
npm http 200 https://registry.npmjs.org/guid/0.0.10
npm http GET https://registry.npmjs.org/guid/-/guid-0.0.10.tgz
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/guid/-/guid-0.0.10.tgz
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/extend
/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2: node: command not found
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node_darwin_x64" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "install" "/Users/tvermeir/.atom/.node-gyp/.atom/.apm/terminal/0.28.0/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/jb/3wmdzhj53jb5l4tkwchty0w80000gn/T/apm-install-dir-11437-10619-1bk5huy
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/jb/3wmdzhj53jb5l4tkwchty0w80000gn/T/apm-install-dir-11437-10619-1bk5huy/npm-debug.log
npm ERR! not ok code 0
```

**Comment by rschiang** [comment] 2014-04-08 13:00
+1, have the exact problem, seems caused by pty.js?

```
/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2: node: command not found
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
```

**Comment by Glavin001** [comment] 2014-04-08 23:16
+1, myself as well.

```
> pty.js@0.2.4 install /private/var/folders/lw/ct2vyvzs04gd_l8bn8794t800000gn/T/apm-install-dir-11438-71129-1avunnn/node_modules/terminal/node_modules/pty.js
> node-gyp rebuild


npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/guid/0.0.10
npm http GET http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http GET https://registry.npmjs.org/fs-plus
npm http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 304 https://registry.npmjs.org/guid/0.0.10
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/extend
npm http 200 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/property-accessors
/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/node-gyp-bin/node-gyp: line 2: node: command not found
npm http 304 https://registry.npmjs.org/mixto
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node_darwin_x64" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "install" "/Users/glavin/.atom/.node-gyp/.atom/.apm/terminal/0.28.0/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /private/var/folders/lw/ct2vyvzs04gd_l8bn8794t800000gn/T/apm-install-dir-11438-71129-1avunnn
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/lw/ct2vyvzs04gd_l8bn8794t800000gn/T/apm-install-dir-11438-71129-1avunnn/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Glavin001** [comment] 2014-04-08 23:20
The following worked for me:

``` bash
apm install terminal
```

From https://github.com/atom/terminal/issues/28#issuecomment-38562442

**Comment by rschiang** [comment] 2014-04-09 04:07
@Glavin001 Yes, it worked for me too. Not sure why it failed in GUI, missing `PATH` variable?

**Comment by LeCoupa** [comment] 2014-04-09 06:55
Yes works for me too!

**Comment by dustintheweb** [comment] 2014-04-10 11:41
Also confirming the issue / workaround. GUI install barf's, command line install works.

**Comment by Glavin001** [comment] 2014-04-10 14:38
>  Not sure why it failed in GUI, missing PATH variable?

I think so. I also noticed that when using Atom Terminal the `PATH` is also incorrect, and breaks some installed command line tools.

**Comment by schaary** [comment] 2014-04-10 16:12
I had the same issue - in the GUI and on the command line. The reason, in my case, was that nodejs was missing. So I installed it with brew `brew install nodejs` on mavericks and then `apm install terminal` works fine.

**Comment by schmty** [comment] 2014-04-19 20:55
`apm install terminal` worked for me as well.

**Comment by DanAlbert** [comment] 2014-04-26 06:28
Can confirm that the issue is not having node installed. Was able to install through the GUI after running `brew install node` and then restarting the editor.

**Comment by schmty** [comment] 2014-04-26 20:20
I have node installed but have noticed that when I use the plugin `script` it fails to find node in my PATH

**Comment by lee-dohm** [comment] 2018-08-23 19:47
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Closed as completed by lee-dohm** 2018-08-23 19:47 UTC
Labels: bug
